#!/bin/bash

# Env Information
: ${USERNAME:=siteRootAdmin}
: ${PASSWORD:=password}
: ${COMPOSE_OPT:=-H tcp://localhost:9999}

docker-compose ${COMPOSE_OPT} exec mongors1n1 bash -c "echo 'rs.initiate();sleep(1000);' | mongo admin"
docker-compose ${COMPOSE_OPT} exec mongors1n1 bash -c "echo 'db.createUser({user: \"${USERNAME}\", pwd: \"${PASSWORD}\", roles: [ { role: \"root\", db: \"admin\" } ] });' | mongo admin"

echo "Intializing replica rs1 set"
replicate="cfg = rs.conf(); cfg.members[0].host = \"mongors1n1\"; rs.reconfig(cfg); rs.add(\"mongors1n2\"); rs.add(\"mongors1n3\"); rs.status();"
docker-compose ${COMPOSE_OPT} exec mongors1n1 bash -c "echo '${replicate}' | mongo  -u ${USERNAME} -p ${PASSWORD} --authenticationDatabase admin"

